env:
  browser: true
  es2021: true
extends: "airbnb-base/legacy"
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-var: "error",
  quotes: ["error", "double"],
  linebreak-style: 0
}
